name = "ViterbiDecoder"
uuid = "5f0870c7-49c9-4542-b5f1-5d9ed4caea51"
authors = ["Soeren Schoenbrod <soeren.schoenbrod@juliacomputing.com> and contributors"]
version = "0.1.0"

[deps]
viterbi_jll = "dd422b0c-1f95-5ffb-9e80-de3947502723"

[compat]
viterbi_jll = "0.1.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
